% Image 1 : Original WF
% Mask 1 :Neuf Fiber detection combine inverse intensity mask;
% Image 2 : TIMImage2;
% Mask 2: Neuf Fiber detection combine inverse intensity mask;

% Performs 2D TIM with a global threshold
% With the threshold, the code will first generate a mask1 that combine the mask based on the
% WF Image1 intensity inverse and fiber detection on original widefield image.
% Then, it will project the mask1 to DMD. With mask1, we get Image2 and we call it TIMImage2
% Apply fiber detection on Image2, we get a mask2 which can futher improve image quality.
% Use Psychtoolbox (http://psychtoolbox.org/) to speed up the DMD flipping.
% This is a code built for efficency

clc
close all
clear all


%% set imaging parameters
SampleName = 'PVD';
SampleNum = '68a';  

CameraExposureTime=0.01; % unit is second

LEDIntensityWF = 25; 
LEDIntensityTIM = LEDIntensityWF*2; % 0-100 linear intensity representation of Sola intensity

ObjectiveMag = 60; % you can choose from 2, 10, 20, 40, 60. For 60x, it is a oil immersionobjective
Density = 2; % this is the neuron fiber density, use 2 by default
ExperimentPeriodLength = 30; % how long will the neuron activity last, unit in second.
ImagingInterval = 0; % the gap time between each imaging,unit in second.
pausePeriodInBetween = 0;

WidefieldCompareNeeded = 1; % if it is 1, a widefield comparsion imaging will start right after the TIM imaging

Darkcount = 0; % 0 for the Hamamatsu camera
IniDarkThreshold = 400;
IniBrightThreshold = 50000;

KeepMetaData = 1; % if you want to keep all TIM process data, use 1, if no keep, use 0;

load('ZPosition.mat', 'zposition'); % generated by LiveHamWithDMD.m, so the live imaging defined Z is revisited
load('HamamatsuROI.mat', 'ROI'); % generated by LiveHamWithDMD.m
load('TIM_random_move.mat','Random_move'); % generated by the generateRandomMove.m

se = strel('square',9); % creates a square structuring element whose width is 5 pixels, to dilate fibers in image
% for motion compensation tracking, we use a larger dilation, which is 9,
% 11, 13

ImageLowLimitForWFShow = 50;
ImageUpLimitForWFShow = 25000;
ImageLowLimitForTIMShow = 50;
ImageUpLimitForTIMShow = 5000;
 
Date = datetime('now','TimeZone','local','Format','yMMd');
DateChar = string(Date);

SampleNumStr = num2str(SampleNum);
DensityStr = num2str(Density);
ImageNameSec1 = strcat(DateChar,'-2DTIM',SampleName,'-',SampleNumStr,'-Density',DensityStr);

UseAOI = 1;
ImageWidth = ROI(3);
ImageHeight = ROI(4);
ImageAspectRatio = ImageWidth/ImageHeight;

NominalImageHeight = 1868;% calibrated DMD height on our Hamamatsu camera
NominalImageWidth = 2304; % calibrated DMD width on our Hamamatsu camera
ImageToNominalImageRatio = ImageHeight / NominalImageHeight;


%% show initial white background to DMD
DMDHeight = 1600; % this 1600*2560 is the DMD resolution we use
DMDWidth = 2560;
IniBackgrImage = uint8(255 * ones(DMDHeight,DMDWidth));
DarkBackgrImage = uint8(zeros(DMDHeight,DMDWidth));
Im=IniBackgrImage;

% Open a full-screen window on the DMD monitor
dmdScreenID = 2;
[windowPtr, windowRect] = PsychImaging('OpenWindow', dmdScreenID, [255,255,255]);

% Generate or update your pattern (imageMatrix)
tex = Screen('MakeTexture', windowPtr, IniBackgrImage);
% Draw the texture (in one or two lines)
Screen('DrawTexture', windowPtr, tex, [], []);
% project the image pattern immediately
Screen('Flip', windowPtr, 0, 0, 2); % [vbl, StimulusOnsetTime, FlipTime] = Screen('Flip', windowPtr, when, dontclear, dontsync);

pause(2)

%% initialize camera
disp('setting Hamamatsu Camera...')
imaqhwinfo('hamamatsu');

imageFormat = 'MONO16_2304x2304_FastMode';
vid = videoinput('hamamatsu', 1, imageFormat);
src = getselectedsource(vid);

vid.ROIPosition = ROI; % set AOI

src.ExposureTime = CameraExposureTime;
vid.FramesPerTrigger = inf;
vid.TriggerRepeat = 0;

triggerconfig(vid, 'immediate'); % you can also use 'immediate' to replace 'manual'

src.HotPixelCorrectionLevel = 'standard';

vid.LoggingMode = 'memory';
src.TriggerPolarity = 'positive';

disp('Starting acquisition...');
start(vid)


%% create image visulizing windows for future use
ImageBuf = uint16(zeros(ImageHeight, ImageWidth)); 
FigureForCheck = figure('Name','Live','NumberTitle','off','color','r');

CheckhAxesWF = subplot(1,2,1);
CheckImageWF = imshow(ImageBuf,[ImageLowLimitForWFShow ImageUpLimitForWFShow],'Parent',CheckhAxesWF,'border','tight');
title('Wide Field image')

CheckhAxesTIM = subplot(1,2,2);
CheckImageTIM = imshow(ImageBuf,[ImageLowLimitForTIMShow ImageUpLimitForTIMShow],'Parent',CheckhAxesTIM,'border','tight');
title('TIM image')

set(FigureForCheck,'position',[500,200,3200,2000]); % to maintain the figure size while move it to a new location

%% Setup Nikon microscope
addpath('C:\Program Files\Nikon\Ti2-SDK\bin'); 
addpath('E:\Yao\Nikon\ScanningPattern');
addpath('E:\Yao\Nikon\AndorSDK3');
!regsvr32 /s NkTi2Ax.dll;
% global ti2;
ti2 = actxserver('Nikon.Ti2.AutoConnectMicroscope');

Positions = load('Position.mat');
xposition =Positions.xposition;
yposition =Positions.yposition;
zposition =Positions.zposition;

ti2.XPosition.Value = xposition;
ti2.YPosition.Value = yposition;
ti2.ZPosition.Value = zposition;


ti2.iXPOSITIONSpeed=7; 
ti2.iYPOSITIONSpeed=7;
ti2.iZPOSITIONSpeed=7;

ti2.iLIGHTPATH=2; % 2 for light to the right camera, 4 for light to left camera
 
ti2.iTURRET2SHUTTER=0;
ti2.iTURRET2POS=1;
ti2.iDIA_LAMP_Switch=0;
ti2.iDIA_LAMP_Pos=0;
ti2.iTURRET1SHUTTER=1;
ti2.iTURRET2POS=1;

switch ObjectiveMag
    case 2
        ti2. iNOSEPIECE=6;
    case 10
        ti2. iNOSEPIECE=2;
    case 20
        ti2. iNOSEPIECE=3;
    case 40
        ti2. iNOSEPIECE=1;
    case 60
        ti2. iNOSEPIECE=5;
end

ti2.ZPosition.Value = zposition;
pause(0.5)
ti2.ZPosition.Value = zposition;

%% Setup Sola illumination
% we use Sola for illumination
disp('Setting up the Sola illumination...')
SolaOn

%% image acquisition
Sola(LEDIntensityWF); % Use Sola(0) to keep light temporarily off

tex = Screen('MakeTexture', windowPtr, 255-IniBackgrImage);
Screen('DrawTexture', windowPtr, tex, [], []);
Screen('Flip', windowPtr, 0, 0, 2); 

DarkThreshold = IniDarkThreshold;
BrightThreshold = IniBrightThreshold;

pause(CameraExposureTime + 0.05) % wait because of DMD response time

% get the Image1 and generate intensity inverse combined fiber detector mask1
WideFieldImage1 = getsnapshot(vid); % acquire the widefield image

InitialImage = double(WideFieldImage1);

set(CheckImageWF,'CData',WideFieldImage1); % refresh the WF image to a new one
drawnow

Sola(LEDIntensityTIM); % light for TIM on
% Fiber Segmentation
FibersInImage = NeufRatioLocalDensity(InitialImage, Darkcount, Density); % returns all pixels that are stronger than threshold.
FibersInImageDilated = double(imdilate(FibersInImage,se));

% Bandlimitted intensity inverse
InitialImageThre = InitialImage;
InitialImageThre(InitialImage<DarkThreshold) = BrightThreshold;
InitialImageThre(InitialImage>BrightThreshold) = BrightThreshold;
InitialImageUint8 = (InitialImageThre./BrightThreshold)*255;
InitialImageUint8(InitialImageUint8<1) = 1;
InitialImageUint8Inv = floor(255-InitialImageUint8);
InitialImageUint8Inv = InitialImageUint8Inv+1; % we still give bright signal a little bit light

Mask1 = InitialImageUint8Inv .* FibersInImageDilated; % combine the edge detected mask with previous intensity inverse mask

FiberMaskUint8Resize = imresize(Mask1,[DMDHeight*ImageToNominalImageRatio  DMDHeight*ImageAspectRatio*ImageToNominalImageRatio],'bilinear');
FiberMaskUint8ResizeMax = max(FiberMaskUint8Resize(:));
FiberMask1Uint8Pattern = uint8(floor((FiberMaskUint8Resize/FiberMaskUint8ResizeMax)*255));
FiberMask1Uint8Pattern = 255-centerSmallMatrix(FiberMask1Uint8Pattern, DarkBackgrImage); % center the generated pattern and inverse it for the inversed DMD
FiberMask1Uint8Pattern = flip(FiberMask1Uint8Pattern,1); % because DMD up and down is flipped

tex = Screen('MakeTexture', windowPtr, FiberMask1Uint8Pattern);
Screen('DrawTexture', windowPtr, tex, [], []);
Screen('Flip', windowPtr, 0, 0, 2); 

%% get an improved intermediate TIM Image2
pause(CameraExposureTime + 0.05)
TIMImage2 = getsnapshot(vid); % acquire the TIM intermediate image
set(CheckImageTIM,'CData',TIMImage2); % refresh the WF image to a new one
drawnow

%% generate a Neuf fiber and intensity inverse combined mask2
FibersInImage  = NeufRatioLocalDensity(double(TIMImage2), Darkcount, Density/2);
FibersInImageDilated = double(imdilate(FibersInImage,se));

Mask2Buff1  = InitialImageUint8Inv .* FibersInImageDilated; % combine the edge detected mask with previous intensity inverse mask
Mask2Buff2 = Mask2Buff1;
Mask2Buff2(Mask2Buff2>2) = 255; % for all those illuminating location, make them bright all the way

Mask2 = Mask2Buff2;

FiberMaskUint8Resize = imresize(Mask2Buff1,[DMDHeight*ImageToNominalImageRatio  DMDHeight*ImageAspectRatio*ImageToNominalImageRatio],'bilinear');
FiberMaskUint8ResizeMax = max(FiberMaskUint8Resize(:));
FiberMask2Uint8Pattern = uint8(floor((FiberMaskUint8Resize/FiberMaskUint8ResizeMax)*255));
FiberMask2Uint8Pattern(FiberMask2Uint8Pattern>2) = 255;
FiberMask2Uint8Pattern = 255-centerSmallMatrix(FiberMask2Uint8Pattern, DarkBackgrImage); % center the generated pattern and inverse it for the inversed DMD
FiberMask2Uint8Pattern = flip(FiberMask2Uint8Pattern,1);

tex = Screen('MakeTexture', windowPtr, FiberMask2Uint8Pattern);
Screen('DrawTexture', windowPtr, tex, [], []);
Screen('Flip', windowPtr, 0, 0, 2); 

flushdata(vid);

%% Start the neuron activity tracking
buff_frame_num = 5*(1/CameraExposureTime);
ImageNumNeedToAcquire = ceil(ExperimentPeriodLength / (CameraExposureTime+ImagingInterval));
TIMNeuronActivityImage = zeros(ImageHeight, ImageWidth, ImageNumNeedToAcquire+buff_frame_num);

AcquireNumChar = strcat('Will acquire', " ", num2str(ImageNumNeedToAcquire), " ", 'images, with total time of'," ", num2str(ExperimentPeriodLength)," seconds");
disp(AcquireNumChar)
disp('Neuron activity tracking timelapse imaging start')

Sola(LEDIntensityTIM);
pause(0.2)

trackingDataNum = 1;

% mask generation Neuf filter parameters
ImageRatioOut = zeros(ImageHeight,ImageWidth);
ImageRatioOutLow = zeros(ImageHeight,ImageWidth);
Gx = [-ones(5) 2*ones(5) -ones(5)]; % the defacult fiber thickness is 5
Gy = Gx';

XNumber = 50; % to divide an image to 50*50 subimages
SubMatrixX = floor(ImageHeight / XNumber); % how many subimages in the horizontal direction

YNumber = 50; % to divide an image to 50*50 subimages
SubMatrixY = floor(ImageWidth / YNumber); % how many subimages in the vertical direction
SubImageSize = XNumber * YNumber;
DensityPixelNumber = SubImageSize * (Density/100); % for a giving density, how many '1' pixels will be in the subimage
OrigImage = zeros(ImageHeight,ImageWidth);
OrigImage = gpuArray(OrigImage);

TimeSpent = zeros((ImageNumNeedToAcquire+50)/10, 1);

Frame = 0;
move_num = 1;

tic
for i = 1:10:ImageNumNeedToAcquire+buff_frame_num
%     tic;
    TIMNeuronActivityImage(:,:,i) = getsnapshot(vid); % acquire a TIM image of neuron activity
    OrigImage = double(TIMNeuronActivityImage(:,:,i)) - Darkcount;
    ImageX = double(imfilter(OrigImage,Gx,'replicate'));
    
    ti2.XPosition.Value = ti2.XPosition.Value + (Random_move(move_num))/2; % 1 is 0.1 um
    ti2.YPosition.Value = ti2.YPosition.Value + (Random_move(move_num+500))/2; % 1 is 0.1 um
    move_num = move_num + 1;
    Frame = Frame + 1;

    TIMNeuronActivityImage(:,:,i+1) = getsnapshot(vid); % acquire a TIM image of neuron activity
    ImageX(ImageX<0) = 0; % rectify
    ImageY = double(imfilter(OrigImage,Gy,'replicate'));
    ImageY(ImageY<0) = 0;
    Frame = Frame + 1;

    TIMNeuronActivityImage(:,:,i+2) = getsnapshot(vid); % acquire a TIM image of neuron activity
    ImageMagnitude = sqrt(ImageX.^2+ImageY.^2); % this is the Neuf enhanced image
    RatioImage = ImageMagnitude./OrigImage; % this is the Ratio image
    Frame = Frame + 1;


    TIMNeuronActivityImage(:,:,i+3) = getsnapshot(vid); % acquire a TIM image of neuron activity
    DensityRatioThres = prctile(RatioImage(:), 100 - Density,'all');
    Frame = Frame + 1;

    TIMNeuronActivityImage(:,:,i+4) = getsnapshot(vid); % acquire a TIM image of neuron activity
    ImageRatioOut(RatioImage > DensityRatioThres) = 1; % segmentation
    ImageRatioOut(ImageMagnitude < 2000) = 0;
    Frame = Frame + 1;
    
    TIMNeuronActivityImage(:,:,i+5) = getsnapshot(vid); % acquire a TIM image of neuron activity
    ImageRatioOut = bwareaopen(ImageRatioOut,4,8); % remove very small connected pixels
    FibersInImageDilated = double(imdilate(ImageRatioOut,se));
    Mask2Buff1  = InitialImageUint8Inv .* FibersInImageDilated; % combine the edge detected mask with previous intensity inverse mask
    Mask2Buff2 = Mask2Buff1;
    Frame = Frame + 1;

    TIMNeuronActivityImage(:,:,i+6) = getsnapshot(vid); % acquire a TIM image of neuron activity
    Mask2Buff2(Mask2Buff2>2) = 255; % for all those illuminating location, make them bright all the way
    Mask2 = Mask2Buff2;
    Frame = Frame +1;

    TIMNeuronActivityImage(:,:,i+7) = getsnapshot(vid); % acquire a TIM image of neuron activity
    FiberMaskUint8Resize = imresize(Mask2Buff1,[DMDHeight*ImageToNominalImageRatio  DMDHeight*ImageAspectRatio*ImageToNominalImageRatio],'bilinear');
    FiberMaskUint8ResizeMax = max(FiberMaskUint8Resize(:));
    FiberMask2Uint8Pattern = uint8(floor((FiberMaskUint8Resize/FiberMaskUint8ResizeMax)*255));
    Frame = Frame + 1;

    TIMNeuronActivityImage(:,:,i+8) = getsnapshot(vid); % acquire a TIM image of neuron activity
    FiberMask2Uint8Pattern(FiberMask2Uint8Pattern>2) = 255;
    FiberMask2Uint8Pattern = 255-centerSmallMatrix(FiberMask2Uint8Pattern, DarkBackgrImage); % center the generated pattern and inverse it for the inversed DMD
    FiberMask2Uint8Pattern = flip(FiberMask2Uint8Pattern,1);
    Frame = Frame + 1;
    
    TIMNeuronActivityImage(:,:,i+9) = getsnapshot(vid); % acquire a TIM image of neuron activity
    Frame = Frame + 1 % brief show where you are
    
    tex = Screen('MakeTexture', windowPtr, FiberMask2Uint8Pattern); 
    Screen('DrawTexture', windowPtr, tex, [], []);
    Screen('Flip', windowPtr, 0, 0, 2); 
end
TotalImage = toc;
TotalImageStr = strcat("Total timelapse time with TIM was ", num2str(TotalImage)," seconds");
disp(TotalImageStr)

Screen('Close')
flushdata(vid);
Sola(1) % minimize light to almost 0

% save TIM 2D tracking image
TIMLEDIntensityChar = num2str(LEDIntensityTIM);
ImageNameSec2TIM = strcat('-Sola',TIMLEDIntensityChar);
ImageNameSec3 = '.tif';
TIMFinalMaskName = strcat(ImageNameSec1,ImageNameSec2TIM,'-FinalMask',ImageNameSec3);
disp('Saving TIM-FinalMask image...');
imwrite(Mask2, TIMFinalMaskName);
TIMNeuronActivityImageName = strcat(ImageNameSec1,ImageNameSec2TIM,'-TIMActivityTracking',ImageNameSec3);
TIMNeuronActivityImage = uint16(TIMNeuronActivityImage);
disp('Saving TIM neuron activity tracking timelapse image...');
ImageDescription = strcat('ExposureTime:',num2str(CameraExposureTime),'s;','ExperimentPeriodLength',num2str(ExperimentPeriodLength),"s ",'Image Interval:',num2str(abs(ImagingInterval)),'s;','Sola:',TIMLEDIntensityChar);
SaveZstackImage(TIMNeuronActivityImage, TIMNeuronActivityImageName, 16, ImageDescription);
if KeepMetaData == 1
    TIMImage2Name = strcat(ImageNameSec1,ImageNameSec2TIM,'-MetaTIMImage2',ImageNameSec3);
    Mask1Name = strcat(ImageNameSec1,ImageNameSec2TIM,'-Mask1',ImageNameSec3);
    
    disp('Saving Meta TIM-Image2...');
    imwrite(TIMImage2, TIMImage2Name);
    
    disp('Saving TIM Meta Mask1 image...');
    imwrite(Mask1, Mask1Name);
end

clear TIMNeuronActivityImage
disp('You can check you TIM neuron activity now!');
flushdata(vid);

%% perform widefield neuron activity tracking
WFNeuronActivityImage = zeros(ImageHeight,ImageWidth, ImageNumNeedToAcquire);
if WidefieldCompareNeeded == 1
    Sola(LEDIntensityWF); 
    tex = Screen('MakeTexture', windowPtr, 255-IniBackgrImage); % show solid background to DMD
    Screen('DrawTexture', windowPtr, tex, [], []);
    Screen('Flip', windowPtr, 0, 0, 2);

    pause(0.1)
    AcquireNumChar = strcat('Will acquire', " ", num2str(ImageNumNeedToAcquire), " ", 'widefield images, with total time of'," ", num2str(ExperimentPeriodLength)," seconds");
    disp(AcquireNumChar)

    tic
    for i = 1:ImageNumNeedToAcquire
        WFNeuronActivityImage(:,:,i) = getsnapshot(vid); % acquire a TIM image of neuron activity
    end

    TotalImage = toc;
    TotalImageStr = strcat("Total timelapse time with WF was ", num2str(TotalImage)," seconds");
    disp(TotalImageStr)
end

flushdata(vid);

%% post acquisition cleaning
SolaOff

disp('Acquisition complete');
stop(vid);
delete(vid);
disp('Camera shutdown');

Screen('Close', windowPtr);
disp('DMD pattern off');

%% save all images
WFLEDIntensityChar = num2str(LEDIntensityWF);
ImageNameSec2WF = strcat('-Sola',WFLEDIntensityChar);

WF2DImageName = strcat(ImageNameSec1,ImageNameSec2WF,'-Original',ImageNameSec3);
WFNeuronActivityImageName = strcat(ImageNameSec1,ImageNameSec2WF,'-WFActivityTracking',ImageNameSec3);

disp('Saving Original Wide field  image...');
imwrite(WideFieldImage1, WF2DImageName);

WFNeuronActivityImage = uint16(WFNeuronActivityImage);
disp('Saving WF neuron activity tracking timelapse image...');
ImageDescription = strcat('ExposureTime:',num2str(CameraExposureTime),'s;','ExperimentPeriodLength',num2str(ExperimentPeriodLength),"s ",'Image Interval:',num2str(abs(ImagingInterval)),'s;','Sola:',TIMLEDIntensityChar);
SaveZstackImage(WFNeuronActivityImage, WFNeuronActivityImageName, 16, ImageDescription);

disp('All Done! You can check your widefield neuron activity now!');
close all
