% =========================================================================
% 2D Targeted Illumination Microscopy (TIM) Pipeline
%
% Workflow:
% 1. Acquire Widefield (WF) Image 1.
% 2. Detect fibers (Neuf) + Intensity Inversion -> Generate Mask 1.
% 3. Project Mask 1 -> Acquire Intermediate TIM Image 2.
% 4. Refine fiber detection on Image 2 -> Generate Mask 2.
% 5. Project Mask 2 -> Acquire Final TIM Image.

% if you want high speed TIM, you may use 
% Psychtoolbox (http://psychtoolbox.org/) 
% to speed up the DMD flipping. See TIM_2D_ActivityTracking.m for more info
% =========================================================================

clc; close all; clearvars;

%% 1. Experimental Parameters
SampleName = 'TIM_test';
SampleNum  = '1a';  
CameraExposureTime = 0.05; 
LEDIntensityWF  = 5;
LEDIntensityTIM = LEDIntensityWF * 2; 
ObjectiveMag    = 60; 
Density         = 2; % Target fiber density for segmentation (%)

% Metadata & Performance toggles
KeepMetaData = 1; % Set to 1 to save intermediate masks and images
Darkcount    = 0; % Hamamatsu specific
IniDarkThreshold   = 400;
IniBrightThreshold = 60000;

%% 2. Hardware Initialization & Workspace Setup
load('ZPosition.mat', 'zposition'); % generated by LiveHamWithDMD.m, so the live imaging defined Z is revisited
load('HamamatsuROI.mat', 'ROI');  % generated by LiveHamWithDMD.m
addpath('C:\Program Files\Nikon\Ti2-SDK\bin'); % you need microscope SDK
addpath('E:\Yao\Nikon\ScanningPattern');

% File naming logic
DateChar = string(datetime('now','Format','yMMd'));
BaseFileName = sprintf('%s-2DTIM-%s-%s-Density%0.1f', DateChar, SampleName, num2str(SampleNum), Density);

% DMD Resolution & Initial States
DMDHeight = 1600; DMDWidth = 2560;
IniBackgrImage  = repmat(uint8(255), DMDHeight, DMDWidth);
DarkBackgrImage = zeros(DMDHeight, DMDWidth, 'uint8');

NominalImageHeight = 1868;% calibrated DMD height on our Hamamatsu camera
NominalImageWidth = 2304; % calibrated DMD width on our Hamamatsu camera

%% 3. Setup DMD Projection Figure
% Using white background for an inverted DMD logic
FigureForShow = figure('Name','DMD_Pattern','MenuBar','none','Color','w');
hAxes = axes('Parent', FigureForShow);
BackgroundShow = imshow(IniBackgrImage, 'Parent', hAxes, 'Border', 'loose');
truesize(FigureForShow, [DMDHeight, DMDWidth]);

% Position on second monitor
[Mon2X, Mon2Y, ~, ~] = secondMonitorInfo;
set(FigureForShow, 'Position', [Mon2X-371, Mon2Y-181, DMDWidth, DMDHeight]);

%% 4. Initialize Hamamatsu Camera
disp('Initializing Hamamatsu Camera...');
vid = videoinput('hamamatsu', 1, 'MONO16_2304x2304_FastMode');
src = getselectedsource(vid);
vid.ROIPosition = ROI;
src.ExposureTime = CameraExposureTime;
triggerconfig(vid, 'immediate');
start(vid);

% UI Preview Windows
ImageHeight = ROI(4); ImageWidth = ROI(3);
FigureForCheck = figure('Name','TIM Live Preview','Position',[500,200,1200,600]);
subplot(1,2,1); hWF = imshow(zeros(ImageHeight, ImageWidth, 'uint16'), [50 25000]); title('Widefield');
subplot(1,2,2); hTIM = imshow(zeros(ImageHeight, ImageWidth, 'uint16'), [50 5000]); title('TIM Result');

%% 5. Setup Nikon Ti2 Microscope
!regsvr32 /s NkTi2Ax.dll;
ti2 = actxserver('Nikon.Ti2.AutoConnectMicroscope');
ti2.ZPosition.Value = zposition;
ti2.iLIGHTPATH = 2; % Right port

switch ObjectiveMag
    case 2,  ti2.iNOSEPIECE=6;
    case 10, ti2.iNOSEPIECE=2;
    case 20, ti2.iNOSEPIECE=3;
    case 40, ti2.iNOSEPIECE=1;
    case 60, ti2.iNOSEPIECE=5;
end

%% 6. TIM PHASE 1: Widefield Acquisition & Mask 1 Generation
disp('Phase 1: Generating Mask 1...');
SolaOn; Sola(LEDIntensityWF);
set(BackgroundShow, 'CData', 255-IniBackgrImage); % Full field illumination
drawnow; pause(CameraExposureTime + 0.1); % wait because of DMD response time

% Single clear snapshot
WideFieldImage1 = getsnapshot(vid);
set(hWF, 'CData', WideFieldImage1); drawnow;

% Generate Fiber Mask
InitialImage = double(WideFieldImage1);
se = strel('square', 5);
Fibers = NeufRatioLocalDensity(InitialImage, Darkcount, Density);
FibersDilated = imdilate(Fibers, se);

% Generate Intensity Inverse Mask
ImgThres = InitialImage;
ImgThres(ImgThres < IniDarkThreshold) = IniBrightThreshold;
ImgThres(ImgThres > IniBrightThreshold) = IniBrightThreshold;
ImgInv = floor(255 - (ImgThres ./ IniBrightThreshold * 255)) + 1;

% Combine & Map to DMD
Mask1 = ImgInv .* double(FibersDilated);
FiberMask1Pattern = prepareDMDMask(Mask1, DMDHeight, DMDWidth, ROI);
set(BackgroundShow, 'CData', FiberMask1Pattern); 
drawnow;

%% 7. TIM PHASE 2: Intermediate Acquisition & Mask 2 Generation
disp('Phase 2: Refining Mask 2...');
Sola(LEDIntensityTIM);
pause(CameraExposureTime + 0.1);

TIMImage2 = getsnapshot(vid);
set(hTIM, 'CData', TIMImage2); drawnow;

% Refine Fibers on TIM Image 2
Fibers2 = NeufRatioLocalDensity(double(TIMImage2), Darkcount, Density/2);
Fibers2Dilated = imdilate(Fibers2, se);
Mask2Raw = ImgInv .* double(Fibers2Dilated);

% Boost Signal for projectable mask
Mask2Display = Mask2Raw;
Mask2Display(Mask2Display > 2) = 255; 

FiberMask2Pattern = prepareDMDMask(Mask2Display, DMDHeight, DMDWidth, ROI);
set(BackgroundShow, 'CData', FiberMask2Pattern);
drawnow;

%% 8. TIM PHASE 3: Final Acquisition
disp('Phase 3: Acquiring Final TIM Image...');
pause(CameraExposureTime + 0.1);
TIMImageFinal = getsnapshot(vid);
set(hTIM, 'CData', TIMImageFinal); drawnow;

%% 9. Cleanup & Saving
SolaOff; stop(vid); delete(vid);
ti2.release;

% Save Outputs
imwrite(WideFieldImage1, [BaseFileName, '-WF.tif']);
imwrite(TIMImageFinal,   [BaseFileName, '-TIM.tif']);
if KeepMetaData
    imwrite(TIMImage2, [BaseFileName, '-Intermediate.tif']);
    imwrite(uint8(Mask1), [BaseFileName, '-Mask1.tif']);
end
disp('Process Complete.');

%% Helper Function for Mask Formatting
function pattern = prepareDMDMask(mask, dmdH, dmdW, ROI)
    % Scaling logic
    nomH = NominalImageHeight; % Calibration constant
    scale = ROI(4) / nomH;
    aspect = ROI(3) / ROI(4);
    
    % Resize to DMD physical space
    resized = imresize(mask, [dmdH*scale, dmdH*aspect*scale], 'bilinear');
    scaled = uint8(floor((resized / max(resized(:))) * 255));
    
    % Center, Invert (for DMD), and Flip (Hardware correction)
    pattern = centerSmallMatrix(scaled, zeros(dmdH, dmdW, 'uint8'));
    pattern = flip(255 - pattern, 1);
end